# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  flash:
    desc: Build and flash to esp32
    cmds:
      - tinygo build -target m5stack-core2 -o firmware.bin .
      - tinygo flash -target m5stack-core2 .

  flash-monitor:
    desc: Build and flash to esp32
    cmds:
      - tinygo build -target m5stack-core2 -o firmware.bin .
      - tinygo flash -target m5stack-core2 .
      - tinygo monitor
