# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  TARGET: esp32s3-generic

tasks:
  flash:
    desc: Build and flash to esp32
    cmds:
      - tinygo build -target {{.TARGET}} -o firmware.bin .
      - tinygo flash -target {{.TARGET}} .

  flash-monitor:
    desc: Build and flash to esp32
    cmds:
      - tinygo build -target {{.TARGET}} -o firmware.bin .
      - tinygo flash -monitor -target {{.TARGET}} .
